version: '3.7'

services:
  mongo:
    image: mongo:3.6-xenial
    restart: always
    volumes:
      - ~/data/mongo:/data/db
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081

  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: develop
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./:/app
      - /app/node_modules
    depends_on: 
      - mongo
